### ISSUE TITLE
dyld[486]: Library not loaded: @rpath/SeonSDK.framework/SeonSDK

### ISSUE THREAD

**Issue by Shahin-Sefidgaran** [seontechnologies/seon-ios-sdk-public#7]
Hello
I am facing this issue in Flutter with Seon iOS 4.0.0, it crashes and this is the logs.

```
dyld[486]: Library not loaded: @rpath/SeonSDK.framework/SeonSDK
  Referenced from: <03D13DF4-90CA-3EA3-8854-A314812BE4F6> /private/var/containers/Bundle/Application/AAD49F02-8FA8-4031-A706-08F4C7DBB978/Runner.app/Runner
  Reason: tried: '/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2), '/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2), '/private/var/containers/Bundle/Application/AAD49F02-8FA8-4031-A706-08F4C7DBB978/Runner.app/Frameworks/SeonSDK.framework/SeonSDK' (errno=2), '/private/var/containers/Bundle/Application/AAD49F02-8FA8-4031-A706-08F4C7DBB978/Runner.app/Frameworks/SeonSDK.framework/SeonSDK' (errno=2), '/private/var/containers/Bundle/Application/AAD49F02-8FA8-4031-A706-08F4C7DBB978/Runner.app/Frameworks/SeonSDK.framework/SeonSDK' (errno=2), '/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2), '/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2), '/private/var/containers/Bundle/Application/AAD49F02-8FA8-4031-A706-08F4C7DBB978/Runner.app/Frameworks/SeonSDK.framework/SeonSDK' (errno=2), '/private/var/containers/Bundle/Application/AAD49F02-8FA8-4031-A706-08F4C7DBB978/Runner.app/Frameworks/SeonSDK.framework/SeonSDK' (errno=2), '/private/var/containers/Bundle/Application/AAD49F02-8FA8-4031-A706-08F4C7DBB978/Runner.app/Frameworks/SeonSDK.framework/SeonSDK' (errno=2), '/private/preboot/Cryptexes/OS@rpath/SeonSDK.framework/SeonSDK' (errno=2), '/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2), '/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2), '/private/var/containers/Bundle/Application/AAD49F02-8FA8-4031-A706-08F4C7DBB978/Runner.app/Frameworks/SeonSDK.framework/SeonSDK' (errno=2), '/private/var/containers/Bundle/Application/AAD49F02-8FA8-4031-A706-08F4C7DBB978/Runner.app/Frameworks/SeonSDK.framework/SeonSDK' (errno=2), '/private/var/containers/Bundle/Application/AAD49F02-8FA8-4031-A706-08F4C7DBB978/Runner.app/Frameworks/SeonSDK.framework/SeonSDK' (errno=2), '/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2), '/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2), '/private/var/containers/Bundle/Application/AAD49F02-8FA8-4031-A706-08F4C7DBB978/Runner.app/Frameworks/SeonSDK.framework/SeonSDK' (errno=2), '/private/var/containers/Bundle/Application/AAD49F02-8FA8-4031-A706-08F4C7DBB978/Runner.app/Frameworks/SeonSDK.framework/SeonSDK' (errno=2), '/private/var/containers/Bundle/Application/AAD49F02-8FA8-4031-A706-08F4C7DBB978/Runner.app/Frameworks/SeonSDK.framework/SeonSDK' (errno=2), '/System/Library/Frameworks/SeonSDK.framework/SeonSDK' (errno=2, not in dyld cache)
Library not loaded: @rpath/SeonSDK.framework/SeonSDK
  Referenced from: <03D13DF4-90CA-3EA3-8854-A314812BE4F6> /private/var/containers/Bundle/Application/AAD49F02-8FA8-4031-A706-08F4C7DBB978/Runner.app/Runner
  Reason: tried: '/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2), '/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2), '/private/var/containers/Bundle/Application/AAD49F02-8FA8-4031-A706-08F4C7DBB978/Runner.app/Frameworks/SeonSDK.framework/SeonSDK' (errno=2), '/private/var/containers/Bundle/Application/AAD49F02-8FA8-4031-A706-08F4C7DBB978/Runner.app/Frameworks/SeonSDK.framework/SeonSDK' (errno=2), '/private/var/containers/Bundle/Application/AAD49F02-8FA8-4031-A706-08F4C7DBB978/Runner.app/Frameworks/SeonSDK.framework/SeonSDK' (errno=2), '/usr/lib/swift/SeonSDK.framework/SeonSDK' (errno=2, not in dy
dyld config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/usr/lib/libBacktraceRecording.dylib:/usr/lib/libMainThreadChecker.dylib:/usr/lib/libRPAC.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
(lldb)
```

**Comment by sefidgaran** [comment]
Hello @Shahin-Sefidgaran 

I found a solution, I added SeonSDK.xcframework as transitive framework into Target Runner -> General -> Frameworks, Libaries, and Embedded Content as screenshot below:

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/22389242/202877822-f5d729fc-d104-4584-b3e5-8c53cf7e5878.png">

But I have a feeling that this SeonSDK.xcframework should be added automatically to Pods_Runner.framework rather than adding it manually.

Any new solution would be great. :)
Thanks

**Comment by sefidgaran** [comment]
Hi @robertorsulics-seon 
The above solution does not look like a proper way to do it as Seon framework should be loaded automatically without need to embed it manually.
Please check this issue, if there would need a fix for SEON iOS SDK it would be great.
More information:
https://stackoverflow.com/questions/24333981/ios-app-with-framework-crashed-on-device-dyld-library-not-loaded-xcode-6-beta

Thanks

**Comment by sefidgaran** [comment]
Hello,

FYI: This issue has been fixed in my end and I believe it was a local issue. 
Probably it happened by internal bugs about CocoaPod and XCode, you maybe able to fix it by cleaning XCode/Flutter.

Regards.

**Comment by maxim-ivanchuk-idf** [comment]
**@sefidgaran hey!** 
i cleaned XCode/Flutter, derived data and a lot of etc, but i still have this problem 
maybe u can help me, pls?

**Comment by maxim-ivanchuk-idf** [comment]
@robertorsulics-seon can u help pls ?

**Comment by sefidgaran** [comment]
Hi @maxim-ivanchuk-idf 

@Shahin-Sefidgaran has published it as a [SEON Flutter package](https://pub.dev/packages/seon_plugin) which is working in my end.
Please give it a try, hope it will work.
