### ISSUE TITLE
Audio cut out issue in our video player when SEON function triggers

### ISSUE THREAD

**Issue by sefidgaran** [seontechnologies/seon-ios-sdk-public#9]
Hi

This issue observed in iPhone 8 and iPhone X, other devices most likely does not have this issue as I tested on iPhone SE and iPhone 14 which is working fine.

While our video player is playing video, and SEON function triggers, the video sound will completely cut off until the app relaunch. This issue reproduced on other video players as well.

The error info which we received in the log is:

Image:
![image](https://user-images.githubusercontent.com/22389242/220207384-d69624cb-0810-4074-b939-bc74b28c88c9.png)

Text:
`[as_client]     AVAudioSession_iOS.mm:2206  Error: category option 'defaultToSpeaker' is only applicable with category 'playAndRecord'

[as_client]     AVAudioSession_iOS.mm:2382  Failed to set category, error: -50`

FYI: we are using SEON in Flutter by using [this package](https://pub.dev/packages/seon_plugin) which is a simple calling SEON native function from this library.

Please investigate and fix by issuing new update. appreciated.
Look forward to hearing from the SEON team.

Kind Regards,
Farshid

**Comment by robertorsulics-seon** [comment]
Hey Farshid! Thanks for reporting this issue! I will take a look and get back to you.

**Comment by robertorsulics-seon** [comment]
Hey @sefidgaran! We've just realised [5.0.0](https://github.com/seontechnologies/seon-ios-sdk-public#500) where we've addressed this issue.

**Comment by sefidgaran** [comment]
Hi @robertorsulics-seon 

Thanks for the update.

I investigated the issue but it is still exist and not fixed.
I can reproduce it on iPhone X, the difference is :

After SEON 5.0.0 update:
after audio cut out, if I replay the video it has audio.

Before SEON update:
after audio cut out, app has to be killed and launch again to recover audio.

The issue which is audio cut out is still reproducible.
Please investigate.

Thanks
